# try:
#    a = int(input("enter the number: "))
#    print(a + 3)
# except Exception as e:
   # print("some error occured",e)ana   


try:
   a = int(input("enter the number: "))
   print(a + 3)
except Exception as e:
   print("some error occured",e)  